version: '3'
services:
  zoo1:
    image: zookeeper
    hostname: zoo1
    volumes:
      - /home/zoo/data:/data
    ports:
      - "2181:2181"
      - "7001:8080"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == wiki1]
  zoo2:
    image: zookeeper
    hostname: zoo2
    volumes:
      - /home/zoo/data:/data
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == wiki2]
  zoo3:
    image: zookeeper
    hostname: zoo3
    volumes:
      - /home/zoo/data:/data
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == wiki3]
